import Head from "next/head";
import { useEffect } from "react";
import { useEnglish } from "../components/English";

export default function Contact() {
    const [English,setEnglish ]= useEnglish();
   useEffect (()=>{
    
console.log(English);
} )
  return (
    <div>
      <Head>
        <title>Contacto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
