import Head from 'next/head'
import { useEnglish } from '../components/English';

export default function Mobile() {
  const [english, setEnglish] = useEnglish();

  return (
    <div>
      <Head>
        <title>{english ? 'Desarrollo Movil' : 'Mobile Development'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    </div>
  )
}
