import Head from 'next/head'
import { useEnglish } from '../components/English';
import ImageAnimation from '../components/ImageAnimation'

import celPhoto from '../public/assets/celulares-app.png'


export default function Mobile() {
  const [english, setEnglish] = useEnglish();

  return (
    <div className='h-fit flex flex-col items-center'>
      <Head>
        <title>{english ? 'Desarrollo Movil' : 'Mobile Development'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='py-8 w-4/6'>

        <div className='mb-40'> 

          <h1 className='text-3xl mb-12 '>
            {
              english
                  ? 'DESARROLLO MÓVIL' 
                  : 'MOBILE DEVELOPMENT'
            }
          </h1>

          <p className='text-xl'>
            {
              english
                  ? 'Desarrollamos aplicaciones móviles para iOS y Android, nativas, híbridas y en la nube. Comprendemos tus objetivos y creamos estrategias personalizadas. Ofrecemos servicios de mantenimiento y actualización. Contáctanos para crear una experiencia móvil de primera.'
                  : 'We develop mobile applications for iOS and Android, native, hybrid and in the cloud. We understand your objectives and create personalized strategies. We offer maintenance and updating services. Contact us to create a first class mobile experience.' 
            }
          </p>
        </div>

        <div className='h-1/5 fixed bottom-0 left-0 w-full'>
          <ImageAnimation image={celPhoto} alt={'Celular'} bottom={0} right={150} width={400} position={'bottom'}/>
        </div>

      </div>
    </div>
  )
}
