import Head from 'next/head'
import { useEnglish } from '../components/English';

export default function Mobile() {
  const [english, setEnglish] = useEnglish();

  return (
    <div>
      <Head>
        <title>{english ? 'Desarrollo Movil' : 'Mobile Development'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div>
Ofrecemos servicios de desarrollo móvil para ayudar a su empresa a llegar a sus clientes en todas partes. Nuestro equipo de desarrolladores móviles especializados utiliza las últimas tecnologías para crear aplicaciones móviles de alta calidad para iOS y Android. Ofrecemos servicios de desarrollo de aplicaciones nativas, híbridas y en la nube, todo ello adaptado a las necesidades de tu negocio. Trabajamos contigo para comprender tus objetivos y desarrollar una estrategia de aplicaciones móviles que se adapte a tus necesidades específicas. Además, ofrecemos servicios de mantenimiento y actualizaciones para asegurarnos de que tu aplicación siempre esté funcionando de manera óptima. ¡Contáctanos hoy para obtener más información sobre cómo podemos ayudarte a crear una experiencia móvil de primera clase para tus clientes!
</div>
    </div>
  )
}
