import Head from 'next/head'
import { useEnglish } from '../components/English';


export default function SEO() {
  const [english, setEnglish] = useEnglish();

  return (
    <div className='h-fit flex flex-col items-center'>

      <Head>
        <title>SEO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='py-8 w-4/6'>


        <h1 className='text-3xl mb-12 '>
          {
            english
                ? 'SEO' 
                : 'SEO'
          }
        </h1>

        <p className='text-xl'>
          {
            english
                ? 'Ofrecemos servicios de SEO personalizado para aumentar el tráfico orgánico y mejorar el posicionamiento de tu sitio web en los motores de búsqueda. Trabajamos en la optimización de contenido, realizamos un análisis detallado de tu sitio y competidores para identificar oportunidades de mejora y crear una estrategia SEO que se adapte a tus objetivos comerciales.'
                : 'We offer personalized SEO services to increase organic traffic and improve the positioning of your website on search engines. We work on content optimization, conduct a detailed analysis of your website and competitors to identify improvement opportunities and create an SEO strategy that suits your business goals.' 
          }
        </p>

      </div>
    </div>
  )
}
