import Head from 'next/head'

export default function Web() {
  return (
    <div>
      <Head>
        <title>Desarrollo Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    </div>
  )
}
